import { Language, Voice, PricingPlan } from '../types';

export const APP_CONFIG = {
  name: 'Voicera AI',
  tagline: 'Turn Your Text Into Natural Voice',
  subtitle: 'Create realistic AI voices from your text in seconds. Perfect for YouTube videos, podcasts, stories, education, advertisements, and more.',
  version: '2.5.0',
  currentModel: 'gemini-3.8-flash-lite-tts',
  maxCharactersPerRequest: 3000,
  freeTierLimit: 10000,
  creatorTierLimit: 100000,
  proTierLimit: 500000,
};

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', dir: 'ltr', flag: '🇬🇧' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', dir: 'rtl', flag: '🇵🇰' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', dir: 'ltr', flag: '🇮🇳' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', dir: 'rtl', flag: '🇸🇦' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ / پنجابی', dir: 'ltr', flag: '🇵🇰' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', dir: 'ltr', flag: '🇧🇩' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', dir: 'ltr', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', dir: 'ltr', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', dir: 'ltr', flag: '🇩🇪' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', dir: 'ltr', flag: '🇹🇷' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', dir: 'ltr', flag: '🇧🇷' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', dir: 'ltr', flag: '🇮🇹' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', dir: 'ltr', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', dir: 'ltr', flag: '🇰🇷' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', dir: 'ltr', flag: '🇨🇳' },
];

export const AVAILABLE_VOICES: Voice[] = [
  {
    id: 'Kore',
    name: 'Kore',
    gender: 'Female',
    tone: 'Warm, clear, and soothing',
    style: 'Articulate & Empathetic',
    recommendedFor: 'Audiobooks, Urdu/English Stories, Explanations & Meditation',
    languages: ['Urdu', 'English', 'Hindi', 'Arabic', 'Spanish', 'French', 'German', 'Turkish', 'Japanese'],
    previewText: 'Hello! I am Kore. Welcome to Voicera AI, turning your words into lifelike voice.',
    avatarColor: 'from-amber-400 to-rose-500',
  },
  {
    id: 'Puck',
    name: 'Puck',
    gender: 'Male',
    tone: 'Energetic, dynamic, and youthful',
    style: 'Casual & Upbeat',
    recommendedFor: 'YouTube Videos, Social Media, Gaming & Podcasts',
    languages: ['Urdu', 'English', 'Hindi', 'Arabic', 'Spanish', 'French', 'German', 'Turkish', 'Portuguese'],
    previewText: 'Hey there! Puck here. Let us make your YouTube and social media scripts come alive!',
    avatarColor: 'from-cyan-400 to-blue-600',
  },
  {
    id: 'Charon',
    name: 'Charon',
    gender: 'Male',
    tone: 'Deep, resonant, and authoritative',
    style: 'Documentary & Serious',
    recommendedFor: 'Documentaries, Movie Trailers, Corporate Presentations & News',
    languages: ['Urdu', 'English', 'Hindi', 'Arabic', 'Spanish', 'French', 'German', 'Russian'],
    previewText: 'Greetings. I am Charon. Ready to deliver deep, commanding narration for your projects.',
    avatarColor: 'from-indigo-500 to-slate-800',
  },
  {
    id: 'Fenrir',
    name: 'Fenrir',
    gender: 'Male',
    tone: 'Bold, cinematic, and captivating',
    style: 'Dramatic & Storyteller',
    recommendedFor: 'Storytelling, Cinematic Dialogues, Commercials & Trailers',
    languages: ['Urdu', 'English', 'Hindi', 'Arabic', 'Spanish', 'French', 'German', 'Italian'],
    previewText: 'I am Fenrir. Bring power, weight, and vivid emotion to every sentence you write.',
    avatarColor: 'from-emerald-400 to-teal-700',
  },
  {
    id: 'Zephyr',
    name: 'Zephyr',
    gender: 'Female',
    tone: 'Gentle, friendly, and balanced',
    style: 'Conversational & Approachable',
    recommendedFor: 'Customer Support, Daily News, Educational Content & IVR',
    languages: ['Urdu', 'English', 'Hindi', 'Arabic', 'Spanish', 'French', 'German', 'Turkish', 'Bengali'],
    previewText: 'Hi, I am Zephyr. I bring a calm, friendly tone to your educational scripts and apps.',
    avatarColor: 'from-violet-400 to-purple-600',
  },
  {
    id: 'Aoede',
    name: 'Aoede',
    gender: 'Female',
    tone: 'Sophisticated, expressive, and melodic',
    style: 'Poetic & Creative',
    recommendedFor: 'Urdu Poetry, Expressive Podcasts, Literary Arts & High-Emotion',
    languages: ['Urdu', 'English', 'Hindi', 'Arabic', 'Spanish', 'French', 'German', 'Punjabi'],
    previewText: 'Welcome. I am Aoede. Let us turn your poetry, essays, and stories into melodious speech.',
    avatarColor: 'from-fuchsia-400 to-pink-600',
  },
];

export const STYLE_PRESETS = [
  { id: 'natural', label: 'Natural & Conversational', prompt: 'Natural human cadence, warm and conversational tone' },
  { id: 'storyteller', label: 'Storyteller & Audiobook', prompt: 'Engaging, expressive narrative storyteller with dramatic pacing' },
  { id: 'youtube', label: 'Energetic YouTube Creator', prompt: 'Enthusiastic, fast-paced, high energy content creator' },
  { id: 'news', label: 'Professional News Anchor', prompt: 'Clear, crisp, authoritative, professional broadcast cadence' },
  { id: 'calm', label: 'Calm & Soothing', prompt: 'Relaxed, slow, gentle whisper-soft comforting tone' },
  { id: 'commercial', label: 'Persuasive Advertisement', prompt: 'Confident, captivating, polished commercial voiceover' },
];

export const SAMPLE_SCRIPTS = [
  {
    title: 'Urdu Introduction (تعارف)',
    language: 'Urdu',
    voice: 'Kore',
    category: 'Urdu',
    text: 'وائیسیرا اے آئی میں خوش آمدید۔ جدید ترین مصنوعی ذہانت کی مدد سے اپنی کسی بھی اردو تحریر، کہانی، یا یوٹیوب اسکرپٹ کو لمحوں میں انتہائی قدرتی اور پرکشش آواز میں تبدیل کریں۔',
  },
  {
    title: 'Urdu Poetry (شاعری)',
    language: 'Urdu',
    voice: 'Aoede',
    category: 'Urdu',
    text: 'ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے\nبہت نکلے مرے ارمان لیکن پھر بھی کم نکلے۔\nمحبت میں نہیں ہے فرق جینے اور مرنے کا\nاسی کو دیکھ کر جیتے ہیں جس کافر پہ دم نکلے۔',
  },
  {
    title: 'English YouTube Intro',
    language: 'English',
    voice: 'Puck',
    category: 'YouTube',
    text: "Welcome back to the channel! Today, we're diving deep into the next generation of generative AI voice models. Make sure to hit that subscribe button, grab a coffee, and let's get right into it!",
  },
  {
    title: 'Hindi Storytelling',
    language: 'Hindi',
    voice: 'Kore',
    category: 'Hindi',
    text: 'एक समय की बात है, पहाड़ों के बीच बसे एक शांत गाँव में एक समझदार कारीगर रहता था। उसकी कला में कुछ ऐसा जादू था कि हर देखने वाला हैरान रह जाता था।',
  },
  {
    title: 'Documentary Narration',
    language: 'English',
    voice: 'Charon',
    category: 'Documentary',
    text: 'Far beyond the edges of human exploration lies an ocean of silence. Here, ancient stars burn through the cosmic tapestry, whispering secrets older than time itself.',
  },
  {
    title: 'Arabic Greeting',
    language: 'Arabic',
    voice: 'Fenrir',
    category: 'Arabic',
    text: 'مرحبًا بكم في منصة فويسرا للذكاء الاصطناعي. حول نصوصك المكتوبة إلى أصوات واقعية بجودة فائقة ونبرة طبيعية لا مثيل لها.',
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'free',
    name: 'Free Starter',
    description: 'Perfect for trying out natural voice generation and personal experiments.',
    priceMonthly: 0,
    priceAnnual: 0,
    charactersPerMonth: 10000,
    formattedChars: '10,000 chars/mo',
    maxPerRequest: 1500,
    popular: false,
    features: [
      '10,000 characters every month',
      'All 6 Gemini AI voice personas',
      'Urdu, English, Hindi, Arabic & 11+ languages',
      'High quality WAV 24kHz audio download',
      'Full generation history',
      'Standard processing speed',
    ],
    cta: 'Start for Free',
  },
  {
    id: 'creator',
    name: 'Creator Studio',
    description: 'Tailored for YouTubers, podcasters, TikTok creators, and educators.',
    priceMonthly: 15,
    priceAnnual: 12,
    charactersPerMonth: 100000,
    formattedChars: '100,000 chars/mo',
    maxPerRequest: 3000,
    popular: true,
    features: [
      '100,000 characters every month',
      'All 6 voice personas with style fine-tuning',
      'Multi-speaker & emotional speech synthesis',
      'High-speed accelerated generation',
      'Project workspaces & folders',
      'Commercial usage license',
      'Priority audio rendering',
    ],
    cta: 'Upgrade to Creator',
  },
  {
    id: 'pro',
    name: 'Pro Agency',
    description: 'For media studios, audiobooks, agencies, and heavy production teams.',
    priceMonthly: 39,
    priceAnnual: 32,
    charactersPerMonth: 500000,
    formattedChars: '500,000 chars/mo',
    maxPerRequest: 3000,
    popular: false,
    features: [
      '500,000 characters every month',
      'Everything in Creator plan',
      'Unlimited projects & bulk generation',
      'Lossless uncompressed audio export',
      'Custom voice persona prompt guidelines',
      'Dedicated API endpoint access',
      'Priority 24/7 technical support',
    ],
    cta: 'Upgrade to Pro',
  },
];

export const FAQ_ITEMS = [
  {
    question: 'What is Voicera AI?',
    answer: 'Voicera AI is an advanced, production-grade text-to-speech SaaS platform built on the latest Google AI Gemini voice generation technology. It converts any written text into natural, lifelike spoken audio in seconds.',
  },
  {
    question: 'Can I generate Urdu speech?',
    answer: 'Yes! Voicera AI provides native, fluent support for Urdu (اردو) pronunciation, poetry, and dialogue using the Gemini multilingual TTS model. You can write in Urdu script or Roman Urdu and choose voices like Kore or Aoede for rich, authentic delivery.',
  },
  {
    question: 'Can I download the generated audio?',
    answer: 'Yes, absolutely. Every speech generation comes with an instant download button providing the clean, 24kHz WAV audio file directly to your device with zero watermarks.',
  },
  {
    question: 'Does Voicera AI work on mobile?',
    answer: 'Yes! The user interface is engineered with a mobile-first responsive architecture. You can write scripts, switch voices, preview audio, and download files effortlessly on iPhone, Android, and tablets.',
  },
  {
    question: 'Is my API key safe?',
    answer: 'Yes. All Google AI and Gemini communications are executed strictly on the server side via secure backend routes (/api/tts). The API key is stored in server environment variables and is never exposed to the client browser.',
  },
];

export const USE_CASES = [
  { id: 'youtube', title: 'YouTube & TikTok', icon: 'Video', desc: 'Generate punchy, high-energy voiceovers that keep viewers hooked and boost retention.' },
  { id: 'podcasts', title: 'Podcasts & Intros', icon: 'Mic', desc: 'Create intro segments, synthetic co-hosts, and narrative audio episodes with studio warmth.' },
  { id: 'urdu-stories', title: 'Urdu Stories & Poetry', icon: 'BookOpen', desc: 'Expressive Urdu literature, Ghazals, and storytelling with native cadence and emotion.' },
  { id: 'audiobooks', title: 'Audiobooks & Novels', icon: 'Headphones', desc: 'Convert entire chapters into soothing, immersive narrations that transport readers.' },
  { id: 'education', title: 'Education & E-Learning', icon: 'GraduationCap', desc: 'Explain complex concepts in clear, articulate tones across 15+ global languages.' },
  { id: 'ads', title: 'Commercials & Ads', icon: 'Megaphone', desc: 'Produce persuasive, crisp advertisement voiceovers for radio, TV, and digital marketing.' },
];
